### ISSUE TITLE
Add image resources and samplers

### ISSUE THREAD

**Issue by jaebaek** [Igalia/vkrunner#10]
Some shaders use image resources and samplers for them.
To enable testing those shaders, VkRunner needs to support them.

I suggest
1. adding `image` command under `[test]` section as `ssbo` command under `[test]` section.
2. adding `sampler` command under `[test]` section.

Please give me your opinion.

**Comment by bpeel** [comment]
This seems fine to start with. However there are still a lot of details to consider.

How will we set data on the image? What parameters will the `image` command take? Piglit’s shader_runner has a command to make an image with a checkerboard pattern which I think is enough for 99% of the tests.

There are quite a lot of properties on a sampler. Maybe it would make sense to have multiple commands to set them and have sensible defaults. Perhaps something semi-automatic like the thing to set properties on a pipeline could be good.

**Comment by jaebaek** [comment]
I want to suggest the following syntaxes:
```
image <desc set>:<binding> <dim> <extents> <format> [values]+

sampler <desc set>:<binding> <normalized coords> <address mode> <filter mode>

sampledimage <desc set>:<binding> <normalized coords> <address mode> <filter mode> <dim> <extents> <format> [values]+
```

- `image` command defines an [sampled image](https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#descriptorsets-sampledimage) with the given descriptor set, binding, dimension, extents, format, and values. Its descriptor type will be [VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE](https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VkDescriptorType).
  - `<dim>` must be one of `1D, 2D, 3D, Cube, Rect, Buffer, SubpassData` as [dimensions of OpTypeImage](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#Dim) describes.
  - `<extents>` must be `<x>:<y>:<z>` e.g., `640:400:1` for 640 by 400 2D image.
  - `<format>` must be the format matched to one of [VkFormat](https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#features-formats-definition) e.g., `R8G8B8_UNORM` for `VK_FORMAT_R8G8B8_UNORM`.
  - `[values]+` must be one or more values corresponding to the format (e.g., float for `VK_FORMAT_R32G32B32A32_SFLOAT` and unsigned int for `VK_FORMAT_R8G8B8A8_UNORM`) or hex code (e.g., `0xFF0000` for `VK_FORMAT_R8G8B8_UNORM` and hex float for `VK_FORMAT_R32G32B32A32_SFLOAT`).

- `sampler` command defines a [sampler](https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#descriptorsets-sampler) with given descriptor set, binding, whether it uses the normalized coordinate or not, address mode, and filter mode. Its descriptor type will be [VK_DESCRIPTOR_TYPE_SAMPLER](https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VkDescriptorType).
  - `<normalized coords>` must be `TRUE` or `FALSE`.
  - `<address mode>` must be `REPEAT` or `CLAMP_TO_EDGE` or `CLAMP32` or `NONE`.
  - `<filter mode>` must be `NEAREST` or `LINEAR`.
  - For their detailed description, see [OpenCL C Sampler](https://www.khronos.org/registry/OpenCL/sdk/1.0/docs/man/xhtml/sampler_t.html).

- `sampledimage` command has attributes of both `image` and `sampler` commands. It is a [combined image sampler](https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#descriptorsets-combinedimagesampler) and its descriptor type will be [VK_DESCRIPTOR_TYPE_SAMPLER](https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VkDescriptorType).

**Comment by jaebaek** [comment]
In addition, I am worried that the current `ssbo` command does not designate the descriptor set.
Let me know if I am wrong.

Why don't we change syntaxes for `ssbo` as
```
ssbo <desc set>:<binding> <size>
ssbo <desc set>:<binding> subdata <type> <offset> [values]+
```
?

**Comment by jaebaek** [comment]
Since I have not seen a response for a while, I would like to start the implementation.
Please let me know if there is any opinion on it.

**Comment by bpeel** [comment]
Sorry for the late reply.

I think if we want to add descriptor sets it should be made optional, so all of the commands could take either `<desc set>:<binding>` or just `<binding>` where the descriptor set defaults to 0. Perhaps that could be done as a separate PR seeing as it would affect other commands as well.

The samplers have a lot more properties than those mentioned in your proposed command. I think it would be nice to have a simple command that creates a sampler with sensible defaults like:

    sampler <binding>

and then have seperate commands to set the various properties on the sampler like:

    magfilter <binding> <filter>
    minlod <binding> <lod>

Internally it could create all of the combinations of samplers that the script uses and then bind them as appropriate in the same way it does for pipelines.

I think specifying all of the values for an image on a single line would quickly get very unwieldy except for very small images. Piglit’s shader_runner has a command to create a checkerboard texture where you only need to specify two values and it fills the image with them. Perhaps something like that would be more useful in 99% of the cases. I think we should only add a way to specify the exact image contents later on if we really find a usecase where that is needed. If so maybe it would better to do that either with an external PNG or with a separate [section] where we could more conveniently list the values like we do for vertex data.

**Comment by jaebaek** [comment]
Thank you for suggesting the better design.
I will implement it based on your suggestion.

**Comment by jaebaek** [comment]
In terms of the image, could you please explain how we can specify the checkerboard texture?

I checked https://github.com/mesa3d/piglit/blob/master/tests/shaders/glsl-fs-texture2d.shader_test but cannot understand the meaning of `texture rgbw 0 (8, 8)`.

**Comment by bpeel** [comment]
> texture rgbw 0 (8, 8)

I think this version of the command creates an 8x8 texture with red, green, blue and white quadrants as described [here](https://github.com/mesa3d/piglit/blob/master/tests/util/piglit-util-gl.c#L2629).

There is also a command like this:

> texture checkerboard 2 0 (32, 32) (0.5, 0.0, 0.0, 0.0) (0.0, 1.0, 0.0, 0.0)

This defines a 32x32 texture with the top-left and bottom-right as dark red, and the other two quadrants as green.

I’m not really sure which is more useful.

**Comment by jaebaek** [comment]
I just checked a [sampler example](https://github.com/mesa3d/piglit/blob/master/tests/spec/arb_bindless_texture/execution/samplers/explicit-texture-binding.shader_test) and I guess that `0` in `texture rgbw 0 (8, 8)` means binding.

I will add `texture rgbw [descriptor set]:[binding] (width, height)` and `texture rgbw [binding] (width, height)` first.

In terms of `texture checkerboard ...`, it is described [here](https://github.com/mesa3d/piglit/blob/master/tests/util/piglit-util-gl.c#L2462) and I will add it if needed later.

**Comment by jaebaek** [comment]
I realize that `texture` is a confusing command.
Vulkan has three resource types related to image and sampler: 1. the image to sample, 2. the sampler, 3. the combined image sampler (See [here](https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#descriptorsets-sampler)). VkRunner also needs commands to specify all of them.

Why don't we make the following commands:
* `image rgbw [descriptor set]:[binding] (width, height)` and `image rgbw [binding] (width, height)` for [image](https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#descriptorsets-sampledimage).
* `sampler [descriptor set]:[binding]` and `sampler [binding]`for [sampler](https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#descriptorsets-sampler).
* `combined rgbw [descriptor set]:[binding] (width, height)` and `combined rgbw [binding] (width, height)` or `texture rgbw [descriptor set]:[binding] (width, height)` and `texture rgbw [binding] (width, height)` for [combined image sampler](https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#descriptorsets-combinedimagesampler).

**Comment by jaebaek** [comment]
Since Vulkan supports not only those three types but 11 types of resources (see [Vulkan spec chapter 13](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#descriptorsets)), it would be better to add them one by one.

I will add `texture rgbw [descriptor set]:[binding] (width, height)` and `texture rgbw [binding] (width, height)` first for the [combined image sampler](https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#descriptorsets-combinedimagesampler).

**Comment by samuelig** [comment]
Repository moved to https://gitlab.freedesktop.org/mesa/vkrunner. Please re-submit this pull request there.
