### ISSUE TITLE
Please print less on standard output

### ISSUE THREAD

**Issue by dneto0** [Igalia/vkrunner#16]
Right now I get the following output when running an example:

```
$ vkrunner indices.shader_test 
/tmp/vkrunner-8nEFZP
/tmp/vkrunner-8LTVsa
PIGLIT: {"result": "pass" }
```

It seems like the printing of the temp file names is developer debugging output.  I think it should be removed.
The PIGLIT line seems intentional.   I'd like a -q option to make vkrunner completely silent in the success case.  That way vkrunner would fit nicely into a larger test suite.

**Comment by bpeel** [comment]
It’s glslangValidator that prints the temp filename for some reason, not VkRunner. I was thinking of filing a bug about that but I haven’t got around to it.

I agree the `-q` option might be a nice idea. Note that this is only printed by the executable, not by the library, so if the larger test suite is using the library then this won’t happen anyway.

**Comment by bpeel** [comment]
I’ve made a pull request for glslang [here](https://github.com/KhronosGroup/glslang/pull/1472).

**Comment by dneto0** [comment]
> It’s glslangValidator that prints the temp filename for some reason, not VkRunner.

Ah, that's why I couldn't find it in vkrunner.  :-)

Thanks
