### ISSUE TITLE
Can you create a license file explicitly?

### ISSUE THREAD

**Issue by jaebaek** [Igalia/vkrunner#3]
Licenses of files created by both Intel and Igalia look like MIT license, but could you please explicitly create a license file? If you can do it, it would help me a lot. Thanks!

**Comment by bpeel** [comment]
I’m not exactly sure what I can put in the license file because the code contains files taken from Piglit with slightly different copyright notices. Would it help if I included a file like [Piglit’s summary of the licensing](https://cgit.freedesktop.org/piglit/tree/COPYING)?

**Comment by jaebaek** [comment]
Hmm .. if it is not that heavy task, the file like the link will be nice. Actually, the current way to specify the license does not have critical problem, but explicitly specifying it would be useful for people who want to check it quickly.
