### ISSUE TITLE
Enhance preprocessing

### ISSUE THREAD

**Issue by jaebaek** [Igalia/vkrunner#33]
Currently, we support the precompilation. If we make it as a general preprocess, it would be more useful.
Some users can have following needs:
- Use shaders written in Opencl C, HLSL
- Test various options of a shader compiler e.g., `--target-env vulkan1.1` option for `glslangValidator`
  - A/B test with different options with a single VkRunner script
- Test with different compiler e.g., two different builds of `glslangValidator` without rebuilding VkRunner

The preprocess should support the following:

**P1.** Set up shader compilers by command line options.
We need options for setting up GLSL, HLSL, OpenCL C, spirv-as, and spirv-opt. Someone may want to test two different spirv-opt with a single VkRunner script but I am not really sure that we should support it or not. This allows us to test two different compiler with a single VkRunner script without rebuilding VkRunner.

**P2.** Command line arguments for setting up command line options for those compilers.

**P3.** As an alternative of **P2.**, add a section `[preprocess]` in VkRunner script and put commands for preprocessing in the section e.g.,
```
[preprocessing]
glsl vert --target-env vulkan1.1 -Od -e main
hlsl frag -DAWESOME_EFFECT
```
Commands in `[preprocess]` section must be in the form of `<language> <shader type>` e.g., `glsl vert`.

VkRunner library can provide APIs for **P1** and **P2**.

**Comment by samuelig** [comment]
Repository moved to https://gitlab.freedesktop.org/mesa/vkrunner. Please re-submit this pull request there.
