### ISSUE TITLE
Error when using discontinuous descriptor sets

### ISSUE THREAD

**Issue by jaebaek** [Igalia/vkrunner#44]
I found that VkRunner has a bug when there are discontinuous descriptor sets.

[This](https://github.com/jaebaek/amber/blob/sparse_desc_fix/tests/cases/multiple_ssbo_with_sparse_descriptor_set_in_compute_pipeline.amber) is a script to reproduce the bug.

It works fine if descriptor sets are consecutive numbers from 0 to some positive integer `N`.
However, it does not work if descriptor sets are discontinuous e.g., `1, 3, 5`.

**Comment by bpeel** [comment]
Thanks for reporting the issue. I’ve made a pull request for it in #45.
