### ISSUE TITLE
Port VkRunner to Android

### ISSUE THREAD

**Issue by jaebaek** [Igalia/vkrunner#5]
It would be useful if VkRunner supports tests on Android.
As the first version, it may be a simple app with a simple [native activity](https://developer.android.com/ndk/guides/concepts#naa) and support only hex code shaders generated by `precompile-script.py`.

**Comment by jaebaek** [comment]
@bpeel, could you please assign @jaebaek for this issue?
I cannot assign anyone. Maybe I do not have a permission to do so.

**Comment by bpeel** [comment]
Ok, I have assigned you.

I just had a quick look at the Android documentation and noticed that the API includes a runtime GLSL->SPIR-V compiler. It could be nice to eventually use that. Obviously not necessary to start with though.

**Comment by jaebaek** [comment]
Thank you for the suggestion. Ok let's add the support later.
