### ISSUE TITLE
Missing barriers

### ISSUE THREAD

**Issue by paulthomson** [Igalia/vkrunner#52]
I believe there are missing barriers. I have only considered the case of copying an image from the device to the host (`vkCmdCopyImageToBuffer`), but we probably need barriers for ssbos as well.

Some Android devices we tested work without the barriers, but on others nothing is rendered (there is just a black image, which is perfectly acceptable given that there are no barriers) and so the probe commands fail.

I can submit a PR soon with the barriers added.

**Comment by bpeel** [comment]
I’ve merged the branch. Let’s leave the issue open to remind us to fix it for SSBOs too.

**Comment by bpeel** [comment]
I’ve added PR #56 to address the issue with SSBOs. Any feedback would be much appreciated.

**Comment by bpeel** [comment]
I’ve merged the patch for SSBOs. Thanks for the help.
