### ISSUE TITLE
Add ability to specify SPIRV version per shader

### ISSUE THREAD

**Issue by dj2** [Igalia/vkrunner#57]
For Amber, we need to be able to specify the version of SPIR-V each shader is targetting. Different shaders in a single script can have different SPIR-V versions. To that end, we're planning on adding an optional version to the end of the shader declarations. The default value is 1.0 if not specified.

```
[fragment shader target-1.1]
...
[vertex shader spirv asm target-1.2]
...
```
This would be available in all of the declaration types except for SPIRV-HEX where we assume it's already compiled to the correct spir-v version.

(The name target isn't great but I couldn't think of anything better yet, suggestions?)

**Comment by dj2** [comment]
@dneto @alan-baker

**Comment by samuelig** [comment]
Repository moved to https://gitlab.freedesktop.org/mesa/vkrunner. Please re-submit this pull request there.
