### ISSUE TITLE
Allow to select the physical device with --device-id=

### ISSUE THREAD

**Issue by hakzsam** [Igalia/vkrunner#62]
Hi,

In a multi-GPU scenario, vkrunner doesn't allow to select the physical device with, for example, --device-id=1. It would be nice to have support for it.

Btw, CTS has an option (ie. --deqp-vk-device-id=) which starts from 1. For consistency purposes, it would be nice to follow that thing.

Thanks!

**Comment by hikiko** [comment]
Thanks for opening the issue, as there's a pull request for it, I am closing it.
